config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get "signup", to: 'users#new'
  post "users", to: 'users#create'
  resources :users, except: [:new]
  resources :articles
  resources :categories, except: [:destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord 
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title, presence: true, length:{ minimum: 3, maximum: 50 }
	validates :description, presence: true, length:{ minimum: 3, maximum: 350 }
	validates :user_id, presence: true
	
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord 
	belongs_to :category
	belongs_to :article

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates :name, presence: true, length: {maximum:25, minimum:3}
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :username, presence: true, uniqueness: { case_sensitive: false}, 
		length:{ minimum:3, maximum:25 }
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, presence: true, uniqueness: {case_sensitive: false}, length:{ maximum:105 },
		format: {with: VALID_EMAIL_REGEX }

	has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:danger] = "You must by logged in to perform that action"
			redirect_to root_path
		end
	end



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article , only:[:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		#@articles = Article.paginate(page: params[:page], per_page: 2)
		@articles =Article.paginate page: params[:page], per_page: 5
		puts current_user
	end

	def new
		@article = Article.new
	end

	def create
		#render plain: params[:article]
		@article = Article.new(article_params)
		@article.user=current_user
		@article.save
		if @article.save
			flash[:success]='Article was succesly created'
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def show
	end

	def destroy
		@article= Article.find(params[:id])
		@article.destroy
		flash[:danger]= "Article was Succesfully deleted"
		redirect_to articles_path
	end

	def edit

	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			flash[:notice] = "Upadated Succesfully"
			redirect_to article_path(@article)
		else
			render "new"
		end
	end




	private
		def article_params
			params.require(:article).permit(:title, :description,category_ids:[])

		end
		def set_article
			@article = Article.find(params[:id])
		end

		def require_same_user

			if current_user != @article.user && !current_user.admin?
				flash[:danger]= "you can only delete or edit your articels"
				redirect_to root_path			
			end

		end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 
	before_action :require_admin, except: [:index, :show]
	def index
		@categories=Category.paginate page: params[:page], per_page: 3

	end


	def show
		@category=Category.find(params[:id])
		@category_articles =@category.articles.paginate page: params[:page], per_page: 5

	end


	def new
		@category=Category.new
	end


	def edit
		@category=Category.find(params[:id])
	end

	def update
		@category=Category.find(params[:id])
		if @category.update(category_params)
			flash[:success]='Category was successfully updated'
			redirect_to category_path(@category)
		else
			rener "edit"
		end
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			flash[:success] = "Category was created successfully"
			redirect_to categories_path
		else
			render 'new'
		end 

	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !logged_in? || (logged_in? and !current_user.admin?)
			flash[:danger]='Only admins can perform that action'
			redirect_to categories_path
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  	redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController



	def new


	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id]= user.id
			flash[:succes]="You have succesfully logged in"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "something wrong with login info"
			render 'new'
		end
		
	end

	def destroy
		session[:user_id]= nil
		flash[:success] = 'you have logged out'
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show, :destroy]
	before_action :require_same_user, only: [:edit, :update]
	before_action :require_admin, only: [:destroy]

	def new
		@user = User.new
	end


	def create
		@user= User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success]="user was succesfully created"
			redirect_to user_path(@user)
		else
			flash[:danger]="user is not created"
			render "new"
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success]="Your account informaction was succesfully updated"
			redirect_to articles_path
		else
			flash[:danger]="Account not updated"
			render "edit"
		end

	end

	
	def show
		@user_articles=@user.articles.paginate(page: params[:page], per_page:4)
	end

	def destroy

		@user= User.find(params[:id])
		@user.destroy
		flash[:danger]= "User and all articles created by user have ben deleted"
		redirect_to users_path

	end

	def index
		@users=User.paginate page: params[:page], per_page: 3
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user

		if current_user != @user and !current_user.admin
			flash[:danger]= "You can only edit your own account"
			redirect_to root_path
		end

	end

	def require_admin
		if logged_in? and !current_user.admin
			flash[:danger]= "Only admin users can perform that action"
			redirect_to root_path
			
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user, options = {size: 80})
		gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
		size=options[:size]
		gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt:user.username, class: "img-circle")

	end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2"> 
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article)%>
        </div>
        <div class="article-body">
          <%= truncate(article.description,length: 50) %>
          <div class="article-meta-details">
            <small>
              Created by: <%= article.user.username if article.user %>,
              <%= time_ago_in_words(article.created_at) %>,</br>
              last updated: <%= time_ago_in_words(article.updated_at)%>
            </small>
          </div>
        </div>
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>

        <% end %>
        <% if logged_in? && (current_user == article.user || current_user.admin? ) %>
          <div class="article-actions">

            <%= link_to 'Edit article', edit_article_path(article), class:"btn btn-xs btn-primary" %>

            <%= link_to 'Remove article', article_path(article), method: :delete, data:{confirm: "Are you sure ?"}, class: "btn btn-xs btn-danger" %>

          </div>
        <% end %>
      </div>
    </div>
  </div>
<%end%>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj:@article %>

<div>
	<%= form_for @article, html:{class: "form-horizontal"} do |f|%>
  	<div class="form-group">
    	<%= f.label 'tytuł',class: "col-sm-2 control-label" %> 
    	<div class="col-sm-10">
    		<%= f.text_field :title, class: "form-control",autofocus: true %>
    	</div>
  	</div>

   
  	 <div class="form-group">

    	<%= f.label :description,class: "col-sm-2 control-label" %> 
    	<div class="col-sm-10">
    		<%= f.text_area :description, class: "form-control",rows:10 %>
    	</div>
	</div>
  


    <div class="form-group">
      <div class='row'>
        <div class="col-sm-offset-2 col-sm-8">
          
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            
            <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text }%>

          <% end %>

        </div>
      </div>   
    </div>



  	<div class="form-group">
  		<div class="col-sm-offset-2 col-sm-10">
    		<%= f.submit class: "btn btn-primary btn-lg bb"%>
    	</div>   
  	</div>

	<% end %>
</div>





<div align="center">
	[<%= link_to 'Cancel request and return to articles', articles_path %>]
</div>

app/views/articles/edit.html.erb
<h1 align='center'>  Edit page </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles </h1>


<div align="center">
<%= will_paginate @articles %>
<%= render 'article', obj: @articles %>

<%= will_paginate @articles %>

app/views/articles/new.html.erb
<h1 align='center'> create new article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">

   <% if @article.user %>

      <ul class="listing">

         <div class="row center">

            <div class="col-md-4 col-md-offset-4">

               <li>Created by:</li>

               <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>

               <li class="article-title">

                  <%= link_to @article.user.username, user_path(@article.user) %>

               </li>

               <li><small>

                  <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>

               </small></li>

            </div>

         </div>

      </ul>

   <% end %>

   <h4 class="center description"><strong>Description:</strong></h4>

   <hr>

   <%= simple_format(@article.description) %>

   <% if @article.categories.any?  %>
      <p> Categories: <%= render @article.categories %> </p>
   <% end %>
   <div class="article-actions">

      <% if logged_in? && (current_user==@article.user || current_user.admin )%>

         <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>

         <%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %>

      <% end %>


      <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>

   </div>

</div>

app/views/categories/_category.html.erb
<span class='badge'>
	<%= link_to category.name, category_path(category)%> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj:@category %>

<div>
  <%= form_for @category, html:{class: "form-horizontal"} do |f|%>
    <div class="form-group">
      <%= f.label :name,class: "col-sm-2 control-label" %> 
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control",autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary btn-lg bb"%>
      </div>   
    </div>

  <% end %>
</div>





<div align="center">
  [<%= link_to 'Cancel request and return to articles', articles_path %>]
</div>

app/views/categories/edit.html.erb
<h1 align="center"> Update cateogory name </h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center"> Listing All Categories </h1>

<div align="center">
	<%= will_paginate %>
	<% @categories.each do |category| %>

		<ul class="listing">
			<div class="row">
				<div class='well col-md-4 col-md-offset-4'>
					<li class="article-title">
						<%= link_to "#{category.name}", category_path(category) %>
					</li>
					<li>
						<small><%= pluralize(category.articles.count, "article") %></small>
					</li>
					<% if logged_in? && current_user.admin? %>

			          <div class="article-actions">

			            <%= link_to 'Edit category', edit_category_path(category), class:"btn btn-xs btn-primary" %>

			          </div>
			        <% end %>						
				</div>
			</div>
		</ul>
	<% end %>
	<%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center"> Create new category </h1>


<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center">Category: <%= @category.name %> articles </h1>

<div align="center">
	<% if logged_in? and current_user.admin? %>
	
	<div class='row'>
		<%= link_to 'edit categoty name ', edit_category_path(@category)%>
	</div>
	<% end %>


	<%= will_paginate @category_articles %>
	
	<%= render 'articles/article', obj: @category_articles %>

	<%= will_paginate @category_articles %>

</div>

app/views/layouts/_footer.html.erb
<div class='container'>
	<footer>
		<small>
			copyright &copy; Michal Kanarek
		</small>
		<nav>
			<ul>
				<li> <%= link_to 'About', about_path %> </li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
			<% puts name%>
			<div class='alert alert-<%="#{name}" %>'>
				<a href="#" class="close" data-dismiss="alert">x</a>
				
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to 'Alpha-blog', root_path, class:"navbar-brand", id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'New article', new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'All Categories', categories_path %></li>
              <% Category.all.each do |category|%>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
              <% if logged_in? and current_user.admin? %>
                <li role='separator' class="divider"></li>
                <li><%= link_to "Create new category",new_category_path %></li>
              <% end %>
            </ul>
          </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%if logged_in? %>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= 'Admin' if current_user.admin %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Your Profile', edit_user_path(current_user) %></li>
              <li><%= %></li>
              <li><%= link_to 'View your profile', user_path(current_user)%></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "sign up", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages'%>



  

    <div class='container'>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/pages/about.html.erb
<contrainer display='inline'>
  <div>
    <h3> card1 </h3>
  </div>
  <div>
    <h3> card1 </h3>
  </div>
  <%= link_to 'home',root_path %>
 <!-- <%= image_tag '1.jpeg' %>
  <%= link_to image_tag('1.jpeg'), 'www.mashrurhossain.com' %>
-->
</contrainer>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Alpha-blog</h1>
 
  <%= link_to 'Sign up now' ,signup_path, class:"btn btn-primary btn-lg btn-xlarge" %> </br>

</div>

   

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h3>
      <%= pluralize(obj.errors.count,"error")%> prohibit article from being created
    </h3>
  
    <ul>

      <% obj.errors.full_messages.each do |msg| %>
        <li id="msg">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <div id="error-message">
              <%= msg %>
            </div>
        </li>

      <% end %>
    </ul>
  </div>  
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj:@user %>

<div>
  <%= form_for @user, html:{class: "form-horizontal"} do |f|%>
    <div class="form-group">
      <%= f.label :username,class: "col-sm-2 control-label" %> 
      <div class="col-sm-10">
        <%= f.text_field :username, class: "form-control",autofocus: true %>
      </div>
    </div>

   
     <div class="form-group">

      <%= f.label :email ,class: "col-sm-2 control-label" %> 
      <div class="col-sm-10">
        <%= f.email_field :email, class: "form-control" %>
      </div>
  </div>
  

    <div class="form-group">

      <%= f.label :password ,class: "col-sm-2 control-label" %> 
      <div class="col-sm-10">
        <%= f.password_field :password, class: "form-control" %>
      </div>
  </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg bb")%>
      </div>   
    </div>

  <% end %>
</div>





<div align="center">
  [<%= link_to 'Cancel request and return to articles', articles_path %>]
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>

<%= will_paginate @articles %>

<div align="center">
	<% @users.each do |user| %>

		<ul class="listing">

			<div class="row">

				<div class="well col-md-3 col-md-offset-2">

					<li><%= link_to gravatar_for(user), user_path(user) %></li>

					<li class="article-title">

						<%= link_to user.username, user_path(user) %>

					</li>
					<% if logged_in? and current_user.admin? %>
					<%= link_to "Delete this user", user_path(user), method: :delete,data: {confirm:"Are you sure ? "} %>

					<% end %>
					<li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>

				</div>

			</div>

		</ul>

	<% end %>
</div>

<%= will_paginate @articles %>

app/views/users/new.html.erb
<h1 align="center"> Signup for Alpha Blog </h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username %>'s page </h1>


<div class="row">
	<div class='col-md-4 col-md-offset-4 center'>



	<%= gravatar_for @user, size:150  %>



	</div>
</div>

<h4 align="center">  <%= @user.username %>'s articles  </h4>


<div class="center">
	<%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>

<div class="center">
	<%= will_paginate @user_articles %>
</div>